[workspace]
members = [
    ".",
    "crates/dowsing-core",
    "crates/dowsing-mutators",
    "crates/dowsing-optimizers",
    "crates/dowsing-rng",
    "crates/dowsing-sys",
]
resolver = "3"

[package]
name = "dowsing"
version = "0.1.0"
edition = "2024"

[dependencies]
dowsing-core = { version = "0.1.0", path = "crates/dowsing-core" }
dowsing-mutators = { version = "0.1.0", path = "crates/dowsing-mutators" }
dowsing-optimizers = { version = "0.1.0", path = "crates/dowsing-optimizers" }
dowsing-sys = { version = "0.1.0", path = "crates/dowsing-sys" }
rand = { version = "0.9", features = ["small_rng"] }
rayon = "1.10"
