use super::no_coverage::NoCoverage;
use crate::{
    coverage::{CoverageCapture, CoverageId, CoverageSet},
    sancov::SancovCoverage,
};
use rand::{Rng, rngs::SmallRng};
use std::{
    cmp::Ordering,
    collections::{HashMap, HashSet, VecDeque},
    sync::{Arc, Mutex},
};

pub(super) const DEFAULT_MUTATE_DEPTH: usize = 5;
pub(super) const DEFAULT_CAUTIOUS_MUTATE_DEPTH: usize = 1;
pub(super) const DEFAULT_SEED_RATIO: u64 = 8;
pub(super) const CURIOUS_ENERGY_REFRESH_INTERVAL: u64 = 64;
pub(super) const CAUTIOUS_ENERGY_REFRESH_INTERVAL: u64 = 1024;
pub(super) const MAX_PREFIX_LEN: usize = 4096;
pub(super) const MAX_CORPUS_LEN: usize = 4096;
pub(super) const MAX_REDUCER_TRIED_PREFIXES: usize = 65536;
pub(super) const MAX_DICTIONARY_VALUES: usize = 256;
pub(super) const INTERESTING_BYTES: [u8; 10] = [0, 1, 16, 31, 32, 63, 64, 127, 128, 255];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum Mode {
    Curious,
    Cautious,
}

/// Replayable RNG path produced by [`crate::CaseRng::fork_case`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Case {
    pub(super) seed: u64,
    pub(super) prefix: Vec<u8>,
    pub(super) zero_tail: bool,
    pub(super) draws: Vec<DrawSpan>,
    pub(super) semantics: Vec<SemanticSpan>,
    pub(super) sequences: Vec<SequenceSpan>,
}

impl Case {
    /// Replay this case without recording coverage.
    pub fn replay(self) -> crate::CaseRng<NoCoverage> {
        let mut engine = Engine::new(NoCoverage, Mode::Curious).with_case(self);
        engine.next().expect("seeded replay case should yield")
    }

    #[cfg(test)]
    pub(crate) fn from_raw_parts(seed: u64, prefix: Vec<u8>, zero_tail: bool) -> Self {
        Self {
            seed,
            prefix,
            zero_tail,
            draws: Vec::new(),
            semantics: Vec::new(),
            sequences: Vec::new(),
        }
    }

    #[cfg(test)]
    pub(crate) fn from_raw_parts_with_draws(
        seed: u64,
        prefix: Vec<u8>,
        zero_tail: bool,
        draws: impl IntoIterator<Item = (usize, usize, bool)>,
    ) -> Self {
        Self {
            seed,
            prefix,
            zero_tail,
            draws: draws
                .into_iter()
                .map(|(start, len, word)| {
                    DrawSpan::new(
                        start,
                        len,
                        if word {
                            DrawKind::Word
                        } else {
                            DrawKind::Bytes
                        },
                    )
                })
                .collect(),
            semantics: Vec::new(),
            sequences: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) enum DrawKind {
    Word,
    Bytes,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct DrawSpan {
    pub(super) start: usize,
    pub(super) len: usize,
    pub(super) kind: DrawKind,
}

impl DrawSpan {
    pub(super) fn new(start: usize, len: usize, kind: DrawKind) -> Self {
        Self { start, len, kind }
    }

    pub(super) fn end(self) -> usize {
        self.start.saturating_add(self.len)
    }
}

/// Semantic role of a generated byte span.
///
/// Marking generated structure lets [`cautious`] try domain-shaped reductions before falling back
/// to generic byte shrinking. For example, a harness can mark a collection length as [`Length`] and
/// each generated element as [`Item`].
///
/// [`Length`]: SemanticKind::Length
/// [`Item`]: SemanticKind::Item
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SemanticKind {
    /// Bytes that select the length of a generated collection.
    Length,
    /// Bytes that generated one element of a collection.
    Item,
    /// Bytes that selected one enum variant or choice.
    Variant,
    /// Bytes that generated one field of a larger value.
    Field,
    /// Bytes that generated an opaque scalar value.
    Value,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct SemanticSpan {
    pub(super) start: usize,
    pub(super) len: usize,
    pub(super) kind: SemanticKind,
}

impl SemanticSpan {
    pub(super) fn new(start: usize, len: usize, kind: SemanticKind) -> Self {
        Self { start, len, kind }
    }

    pub(super) fn end(self) -> usize {
        self.start.saturating_add(self.len)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct SequenceSpan {
    pub(super) length_start: usize,
    pub(super) length_len: usize,
    pub(super) items: Vec<SequenceItemSpan>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct SequenceItemSpan {
    pub(super) start: usize,
    pub(super) len: usize,
}

impl SequenceItemSpan {
    pub(super) fn end(self) -> usize {
        self.start.saturating_add(self.len)
    }
}

/// Tuning knobs for [`cautious`] minimization.
///
/// The defaults favor thorough reduction. Large or expensive harnesses can lower the reducer budget,
/// cap generated candidates per pass, or disable havoc fallback after deterministic reductions are
/// exhausted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CautiousOptions {
    pub(crate) reducer_budget: usize,
    pub(crate) pass_candidate_limit: usize,
    pub(crate) draw_limit: usize,
    pub(crate) semantic_span_limit: usize,
    pub(crate) semantic_reductions: bool,
    pub(crate) havoc: bool,
}

impl CautiousOptions {
    /// Build default minimization options.
    pub const fn new() -> Self {
        Self {
            reducer_budget: 8192,
            pass_candidate_limit: 8192,
            draw_limit: 512,
            semantic_span_limit: 4096,
            semantic_reductions: true,
            havoc: true,
        }
    }

    /// Alias for [`Self::new`], matching builder-style configuration APIs.
    pub const fn builder() -> Self {
        Self::new()
    }

    /// Set the maximum internal reducer attempts spent to produce one yielded candidate.
    pub fn with_reducer_budget(mut self, budget: usize) -> Self {
        self.reducer_budget = budget.max(1);
        self
    }

    /// Cap the number of candidate reductions retained for each deterministic reducer pass.
    pub fn with_pass_candidate_limit(mut self, limit: usize) -> Self {
        self.pass_candidate_limit = limit.max(1);
        self
    }

    /// Cap how many recorded RNG draws each draw-aware pass inspects.
    pub fn with_draw_limit(mut self, limit: usize) -> Self {
        self.draw_limit = limit.max(1);
        self
    }

    /// Cap how many semantic spans each semantic pass inspects.
    pub fn with_semantic_span_limit(mut self, limit: usize) -> Self {
        self.semantic_span_limit = limit.max(1);
        self
    }

    /// Enable or disable semantic-span reducer passes.
    pub const fn with_semantic_reductions(mut self, enabled: bool) -> Self {
        self.semantic_reductions = enabled;
        self
    }

    /// Enable or disable havoc fallback after deterministic reductions are exhausted.
    pub const fn with_havoc(mut self, enabled: bool) -> Self {
        self.havoc = enabled;
        self
    }

    pub(super) const fn reducer_budget(self) -> usize {
        self.reducer_budget
    }

    pub(super) const fn pass_candidate_limit(self) -> usize {
        self.pass_candidate_limit
    }

    pub(super) const fn draw_limit(self) -> usize {
        self.draw_limit
    }

    pub(super) const fn semantic_span_limit(self) -> usize {
        self.semantic_span_limit
    }

    pub(super) const fn semantic_reductions(self) -> bool {
        self.semantic_reductions
    }

    pub(super) const fn havoc(self) -> bool {
        self.havoc
    }
}

impl Default for CautiousOptions {
    fn default() -> Self {
        Self::new()
    }
}

/// Coverage and path-size stats for one completed [`crate::CaseRng`] execution.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct CaseCoverage {
    pub(crate) feature_count: usize,
    pub(crate) hit_count_weight: u64,
    pub(crate) bytes_consumed: usize,
}

impl CaseCoverage {
    /// Build coverage stats from all observed parts.
    pub const fn new(feature_count: usize, hit_count_weight: u64, bytes_consumed: usize) -> Self {
        Self {
            feature_count,
            hit_count_weight,
            bytes_consumed,
        }
    }

    /// Number of unique coverage features observed during the execution.
    pub const fn feature_count(self) -> usize {
        self.feature_count
    }

    /// Coarse execution intensity derived from hit-count buckets when available.
    pub const fn hit_count_weight(self) -> u64 {
        self.hit_count_weight
    }

    /// Number of RNG bytes consumed by the execution.
    pub const fn bytes_consumed(self) -> usize {
        self.bytes_consumed
    }
}

impl PartialOrd for CaseCoverage {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for CaseCoverage {
    fn cmp(&self, other: &Self) -> Ordering {
        (
            self.feature_count,
            self.hit_count_weight,
            self.bytes_consumed,
        )
            .cmp(&(
                other.feature_count,
                other.hit_count_weight,
                other.bytes_consumed,
            ))
    }
}

/// Coverage-maximizing RNG iterator.
///
/// Each item is an RNG. The RNG owns a coverage guard; when the item is dropped at the end of the
/// caller's loop body, the guard may record coverage and update the next seed choice.
pub fn curious() -> Curious<SancovCoverage> {
    Curious {
        engine: Engine::new(SancovCoverage::new(), Mode::Curious),
    }
}

/// Code-path-minimizing RNG iterator.
///
/// Seed it with [`Cautious::with_case`]. Each yielded variant records coverage unless the caller
/// excludes it with [`crate::CaseRng::discard`].
pub fn cautious() -> Cautious<SancovCoverage> {
    Cautious {
        engine: Engine::new(SancovCoverage::new(), Mode::Cautious),
    }
}

/// Coverage-maximizing search returned by [`curious`].
pub struct Curious<Capture: CoverageCapture = SancovCoverage> {
    pub(super) engine: Engine<Capture>,
}

/// Code-path-minimizing search returned by [`cautious`].
pub struct Cautious<Capture: CoverageCapture = SancovCoverage> {
    pub(super) engine: Engine<Capture>,
}

pub(super) struct Engine<Capture: CoverageCapture = SancovCoverage> {
    pub(super) shared: Arc<Mutex<State<Capture>>>,
}

#[derive(Debug)]
pub(super) struct State<Capture: CoverageCapture> {
    pub(super) capture: Capture,
    pub(super) mode: Mode,
    pub(super) base_seed: u64,
    pub(super) next: u64,
    pub(super) scheduler: SmallRng,
    pub(super) global: CoverageSet,
    pub(super) coverage_frequency: HashMap<CoverageId, u64>,
    pub(super) min_path_removed_frequency: HashMap<CoverageId, u64>,
    pub(super) min_path_target: CoverageSet,
    pub(super) min_path_target_initialized: bool,
    pub(super) min_path_best: Option<MinPathScore>,
    pub(super) min_path_best_index: Option<usize>,
    pub(super) corpus: Vec<CorpusSeed>,
    pub(super) energy_index: EnergyIndex,
    pub(super) pending_cases: VecDeque<Case>,
    pub(super) cautious_reducer: CautiousReducer,
    pub(super) dictionary: Vec<Vec<u8>>,
    pub(super) cautious_options: CautiousOptions,
    pub(super) executions_since_refresh: u64,
    pub(super) mutate_depth: usize,
    pub(super) seed_ratio: u64,
    pub(super) seed_step: u64,
    pub(super) active_cases: u64,
    pub(super) stats: SearchStats,
}

#[derive(Debug)]
pub(super) struct Active {
    pub(super) seed: u64,
    pub(super) trace: Vec<u8>,
    pub(super) draws: Vec<DrawSpan>,
    pub(super) semantics: Vec<SemanticSpan>,
    pub(super) sequences: Vec<SequenceSpan>,
    pub(super) bytes_consumed: usize,
    pub(super) origin: CandidateOrigin,
}

#[derive(Debug, Clone)]
pub(super) struct CorpusSeed {
    pub(super) seed: u64,
    pub(super) prefix: Vec<u8>,
    pub(super) draws: Vec<DrawSpan>,
    pub(super) semantics: Vec<SemanticSpan>,
    pub(super) sequences: Vec<SequenceSpan>,
    pub(super) coverage: Vec<CoverageId>,
    pub(super) removed: Vec<CoverageId>,
    pub(super) score: usize,
    pub(super) hit_count_weight: u64,
    pub(super) path_len: usize,
    pub(super) nonzero_bytes: usize,
    pub(super) energy: f64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(super) struct MinPathScore {
    pub(super) features: usize,
    pub(super) hit_count_weight: u64,
    pub(super) bytes: usize,
    pub(super) nonzero_bytes: usize,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) enum CandidateOrigin {
    SeededCase,
    CuriousMutation,
    CautiousReduction(ReductionId),
    CautiousHavoc,
}

#[derive(Debug, Clone)]
pub(super) struct CautiousReducer {
    pub(super) epoch: u64,
    pub(super) best_index: Option<usize>,
    pub(super) best_seed: u64,
    pub(super) best_prefix: Vec<u8>,
    pub(super) best_draws: Vec<DrawSpan>,
    pub(super) best_semantics: Vec<SemanticSpan>,
    pub(super) best_sequences: Vec<SequenceSpan>,
    pub(super) pass_index: usize,
    pub(super) cursor: usize,
    pub(super) cached_pass: Option<ReducerPass>,
    pub(super) cached_specs: Vec<ReductionSpec>,
    pub(super) tried_prefixes: HashSet<PrefixFingerprint>,
    pub(super) range_pressure: Vec<u16>,
    pub(super) rejects: u64,
    pub(super) preserves: u64,
    pub(super) exhausted: bool,
}

impl Default for CautiousReducer {
    fn default() -> Self {
        Self {
            epoch: 0,
            best_index: None,
            best_seed: 0,
            best_prefix: Vec::new(),
            best_draws: Vec::new(),
            best_semantics: Vec::new(),
            best_sequences: Vec::new(),
            pass_index: 0,
            cursor: 0,
            cached_pass: None,
            cached_specs: Vec::new(),
            tried_prefixes: HashSet::new(),
            range_pressure: Vec::new(),
            rejects: 0,
            preserves: 0,
            exhausted: true,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) struct PrefixFingerprint {
    pub(super) len: usize,
    pub(super) hash: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) struct ReductionId {
    pub(super) epoch: u64,
    pub(super) pass: ReducerPass,
    pub(super) cursor: usize,
    pub(super) start: usize,
    pub(super) len: usize,
    pub(super) target: u64,
    pub(super) fingerprint: PrefixFingerprint,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(super) enum ReducerPass {
    DrawLength,
    TailTrim,
    DrawDelete,
    WeightedBlockDelete,
    BlockZero,
    WordLower,
    ByteLower,
    RepeatedValue,
    DictionaryRepair,
    SequenceDelete,
    SequenceProject,
    SequenceReplace,
    SemanticLength,
    SemanticDelete,
    SemanticSimplify,
}

#[derive(Debug, Clone)]
pub(super) struct ReductionSpec {
    pub(super) op: ReductionOp,
    pub(super) weight: u64,
}

impl ReductionSpec {
    pub(super) fn start(&self) -> usize {
        match &self.op {
            ReductionOp::SetWord { start, .. }
            | ReductionOp::DeleteRange { start, .. }
            | ReductionOp::DeleteSequenceItems { start, .. }
            | ReductionOp::ProjectSequenceItems {
                replace_start: start,
                ..
            }
            | ReductionOp::ZeroRange { start, .. }
            | ReductionOp::SetByte { start, .. }
            | ReductionOp::ReplaceDictionary { start, .. } => *start,
            ReductionOp::ZeroRepeated { .. } => 0,
        }
    }

    pub(super) fn len(&self) -> usize {
        match &self.op {
            ReductionOp::SetWord { width, .. } => *width,
            ReductionOp::DeleteRange { len, .. }
            | ReductionOp::DeleteSequenceItems { len, .. }
            | ReductionOp::ProjectSequenceItems {
                replace_len: len, ..
            }
            | ReductionOp::ZeroRange { len, .. }
            | ReductionOp::ReplaceDictionary { len, .. } => *len,
            ReductionOp::SetByte { .. } => 1,
            ReductionOp::ZeroRepeated { .. } => 0,
        }
    }

    pub(super) fn target(&self) -> u64 {
        match &self.op {
            ReductionOp::SetWord { target, .. } => *target,
            ReductionOp::DeleteSequenceItems { target_len, .. }
            | ReductionOp::ProjectSequenceItems { target_len, .. } => *target_len as u64,
            ReductionOp::SetByte { value, .. } => *value as u64,
            ReductionOp::ZeroRepeated { value } => *value as u64,
            ReductionOp::ReplaceDictionary {
                dictionary_index, ..
            } => *dictionary_index as u64,
            ReductionOp::DeleteRange { .. } | ReductionOp::ZeroRange { .. } => 0,
        }
    }
}

#[derive(Debug, Clone)]
pub(super) enum ReductionOp {
    SetWord {
        start: usize,
        width: usize,
        target: u64,
        zero_until: Option<usize>,
    },
    DeleteRange {
        start: usize,
        len: usize,
        adjust_first: bool,
    },
    DeleteSequenceItems {
        length_start: usize,
        length_width: usize,
        target_len: usize,
        start: usize,
        len: usize,
    },
    ProjectSequenceItems {
        length_start: usize,
        length_width: usize,
        target_len: usize,
        replace_start: usize,
        replace_len: usize,
        items: Vec<(usize, usize)>,
    },
    ZeroRange {
        start: usize,
        len: usize,
    },
    SetByte {
        start: usize,
        value: u8,
    },
    ZeroRepeated {
        value: u8,
    },
    ReplaceDictionary {
        start: usize,
        len: usize,
        dictionary_index: usize,
    },
}

impl MinPathScore {
    pub(super) fn with_nonzero_bytes(
        feature_count: usize,
        hit_count_weight: u64,
        bytes_consumed: usize,
        nonzero_bytes: usize,
    ) -> Self {
        Self {
            features: feature_count,
            hit_count_weight,
            bytes: bytes_consumed,
            nonzero_bytes,
        }
    }
}

#[derive(Debug, Clone, Default)]
pub(super) struct EnergyIndex {
    weights: Vec<f64>,
    tree: Vec<f64>,
    total: f64,
}

impl EnergyIndex {
    pub(super) fn push(&mut self, weight: f64) {
        self.weights.push(0.0);
        self.tree.push(0.0);
        if self.tree.len() == 1 {
            self.tree.push(0.0);
        }
        self.set(self.weights.len() - 1, weight);
    }

    pub(super) fn set(&mut self, index: usize, weight: f64) {
        let Some(slot) = self.weights.get_mut(index) else {
            return;
        };
        let weight = sanitize_energy(weight);
        let delta = weight - *slot;
        *slot = weight;
        self.total += delta;

        let mut tree_index = index + 1;
        while tree_index < self.tree.len() {
            self.tree[tree_index] += delta;
            tree_index += lowbit(tree_index);
        }
    }

    pub(super) fn rebuild(&mut self, weights: impl IntoIterator<Item = f64>) {
        self.weights = weights.into_iter().map(sanitize_energy).collect();
        self.total = self.weights.iter().sum();
        self.tree.clear();
        self.tree.resize(self.weights.len() + 1, 0.0);
        for index in 1..self.tree.len() {
            self.tree[index] += self.weights[index - 1];
            let parent = index + lowbit(index);
            if parent < self.tree.len() {
                self.tree[parent] += self.tree[index];
            }
        }
    }

    pub(super) fn swap_remove(&mut self, index: usize) {
        if index >= self.weights.len() {
            return;
        }
        let last = self.weights.len() - 1;
        if index == last {
            self.set(last, 0.0);
            self.weights.pop();
            self.tree.pop();
            return;
        }

        let moved = self.weights[last];
        self.set(index, moved);
        self.set(last, 0.0);
        self.weights.pop();
        self.tree.pop();
    }

    pub(super) fn sample(&self, rng: &mut SmallRng) -> Option<usize> {
        if self.weights.is_empty() || !self.total.is_finite() || self.total <= 0.0 {
            return None;
        }

        let mut target = rng.random::<f64>() * self.total;
        let mut index = 0;
        let mut bit = self.weights.len().next_power_of_two();
        while bit > 0 {
            let next = index + bit;
            if next < self.tree.len() && self.tree[next] <= target {
                index = next;
                target -= self.tree[next];
            }
            bit >>= 1;
        }

        Some(index.min(self.weights.len() - 1))
    }
}

fn sanitize_energy(weight: f64) -> f64 {
    if weight.is_finite() && weight > 0.0 {
        weight
    } else {
        1.0
    }
}

fn lowbit(value: usize) -> usize {
    value & value.wrapping_neg()
}

/// Counters for a search run.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SearchStats {
    pub(crate) generated: u64,
    pub(crate) executed: u64,
    pub(crate) accepted: u64,
    pub(crate) coverage_ids: u64,
    pub(crate) mutated: u64,
}

impl SearchStats {
    /// Build stats from all counters.
    pub const fn new(
        generated: u64,
        executed: u64,
        accepted: u64,
        coverage_ids: u64,
        mutated: u64,
    ) -> Self {
        Self {
            generated,
            executed,
            accepted,
            coverage_ids,
            mutated,
        }
    }

    /// Number of RNG cases yielded.
    pub const fn generated(self) -> u64 {
        self.generated
    }

    /// Number of RNG cases finished.
    pub const fn executed(self) -> u64 {
        self.executed
    }

    /// Number of executions retained in the corpus.
    pub const fn accepted(self) -> u64 {
        self.accepted
    }

    /// Number of accumulated coverage IDs.
    pub const fn coverage_ids(self) -> u64 {
        self.coverage_ids
    }

    /// Number of generated cases derived from mutation.
    pub const fn mutated(self) -> u64 {
        self.mutated
    }
}
