use super::{
    optimize::{record_discarded_goal_execution, record_finished_goal_execution},
    prelude::{
        Active, CandidateOrigin, Case, CaseCost, CaseCoverage, MAX_PREFIX_LEN, State, StateCore,
    },
    shrink::merge_dictionary_values,
};
use crate::{
    coverage::{CaptureStart, CoverageCapture, ExecutionFeedback},
    sancov::SancovCoverage,
};
use dowsing_rng::{
    ByteAffinity, DrawSpan, RangeIter as SemanticRangeIter, ScalarSpan, SemanticRng, TraceHandle,
    TraceSnapshot,
};
use parking_lot::Mutex;
use rand::RngCore;
use std::{
    ops::{Range, RangeBounds, RangeInclusive, RangeTo, RangeToInclusive},
    sync::Arc,
};

/// RNG yielded by [`crate::Curious`] and [`crate::Cautious`].
pub struct CaseRng<Capture: CoverageCapture = SancovCoverage> {
    runtime: Arc<Mutex<CaseRuntime<Capture>>>,
    semantic: SemanticRng,
}

struct CaseRuntime<Capture: CoverageCapture = SancovCoverage> {
    pub(super) shared: Arc<Mutex<State<Capture>>>,
    pub(super) trace: TraceHandle,
    pub(super) origin: CandidateOrigin,
    pub(super) session: Option<Capture::Session>,
    pub(super) local_capture: Option<Capture>,
    pub(super) start_error: Option<String>,
    pub(super) finished: bool,
}

impl<Capture: CoverageCapture> CaseRng<Capture> {
    pub(super) fn new(
        shared: Arc<Mutex<State<Capture>>>,
        case: Case,
        origin: CandidateOrigin,
        session: Option<Capture::Session>,
        local_capture: Option<Capture>,
    ) -> Self {
        let semantic = SemanticRng::new(case);
        let trace = semantic.handle();
        Self {
            runtime: Arc::new(Mutex::new(CaseRuntime {
                shared,
                trace,
                origin,
                session,
                local_capture,
                start_error: None,
                finished: false,
            })),
            semantic,
        }
    }

    /// Seed backing this execution.
    pub fn seed(&self) -> u64 {
        self.semantic.seed()
    }

    /// Fork the consumed RNG path into a replayable case.
    pub fn fork_case(&self) -> Case {
        self.semantic.fork_trace()
    }

    /// Generate a length in `range` and return a structured range iterator.
    pub fn range<R>(&mut self, range: R) -> RangeIter<'_, Capture>
    where
        R: RangeBounds<usize>,
    {
        RangeIter::new(self, range)
    }

    /// Generate a shrink-aware integer value in `range`.
    ///
    /// This intentionally shadows [`rand::Rng::random_range`] for integer ranges when called on a
    /// `CaseRng`. The generated bytes encode a shrink rank, so reductions tend toward simpler
    /// semantic values such as `0`, small magnitudes, or the lower bound of positive-only ranges.
    ///
    /// Unsupported range types can still use rand's implementation with fully qualified syntax:
    /// `rand::Rng::random_range(&mut rng, range)`.
    #[track_caller]
    pub fn random_range<T>(&mut self, range: impl ShrinkRange<T>) -> T {
        range.sample(self)
    }

    /// Generate a shrink-aware integer value.
    #[track_caller]
    pub fn random<T: ShrinkRandom>(&mut self) -> T {
        T::sample(self)
    }

    /// Finish this execution immediately and return its coverage stats.
    ///
    /// This consumes the RNG because coverage is only meaningful after the caller has finished
    /// executing the path being measured.
    pub fn coverage(mut self) -> Result<CaseCoverage, String> {
        self.finish(true, CaseCost::zero())
    }

    /// Finish this execution with a domain-specific value cost.
    ///
    /// Lower costs are better. In `cautious()` mode the minimizer uses this cost before coverage
    /// and RNG-path length, so a harness can prefer shorter or simpler reproducing values while
    /// still rejecting non-reproducing values with [`Self::discard`].
    pub fn coverage_with_cost(mut self, cost: impl Into<CaseCost>) -> Result<CaseCoverage, String> {
        self.finish(true, cost.into())
    }

    /// Exclude this execution from coverage feedback when the RNG is dropped.
    pub fn discard(mut self) {
        let _ = self.finish(false, CaseCost::zero());
    }

    fn finish(
        &mut self,
        record_coverage: bool,
        case_cost: CaseCost,
    ) -> Result<CaseCoverage, String> {
        self.runtime.lock().finish(record_coverage, case_cost)
    }

    fn fill_bytes_with_affinity(&mut self, dst: &mut [u8], affinity: ByteAffinity) -> DrawSpan {
        self.runtime.lock().ensure_started();
        self.semantic.fill_bytes_with_affinity(dst, affinity)
    }

    fn record_scalar(&mut self, draw: DrawSpan, span: u128) {
        self.semantic.record_scalar(draw, span);
    }
}

/// Range iterator returned by [`CaseRng::range`].
pub struct RangeIter<'a, Capture: CoverageCapture = SancovCoverage> {
    runtime: Arc<Mutex<CaseRuntime<Capture>>>,
    inner: SemanticRangeIter<'a>,
}

impl<'a, Capture: CoverageCapture> RangeIter<'a, Capture> {
    fn new<R>(rng: &'a mut CaseRng<Capture>, range: R) -> Self
    where
        R: RangeBounds<usize>,
    {
        rng.runtime.lock().ensure_started();
        let runtime = Arc::clone(&rng.runtime);
        let inner = rng.semantic.range(range);
        Self { runtime, inner }
    }
}

impl<'a, Capture: CoverageCapture> Iterator for RangeIter<'a, Capture> {
    type Item = CaseRng<Capture>;

    fn next(&mut self) -> Option<Self::Item> {
        self.inner.next().map(|semantic| CaseRng {
            runtime: Arc::clone(&self.runtime),
            semantic,
        })
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.inner.size_hint()
    }
}

impl<Capture: CoverageCapture> ExactSizeIterator for RangeIter<'_, Capture> {}

/// Integer range syntax supported by [`CaseRng::random_range`].
pub trait ShrinkRange<T> {
    /// Draw one shrink-aware value from this range.
    fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> T;
}

/// Integer values supported by [`CaseRng::random`].
pub trait ShrinkRandom: Sized {
    /// Draw one shrink-aware value.
    fn sample<Capture: CoverageCapture>(rng: &mut CaseRng<Capture>) -> Self;
}

trait NativeUnsigned: Copy + Ord + Eq {
    const ZERO: Self;
    const ONE: Self;

    fn to_u128(self) -> u128;
    fn wrapping_add(self, rhs: Self) -> Self;
    fn wrapping_sub(self, rhs: Self) -> Self;
    fn saturating_mul(self, rhs: Self) -> Self;
    fn div2(self) -> Self;
    fn is_even(self) -> bool;
    fn draw_rank<Capture: CoverageCapture>(rng: &mut CaseRng<Capture>, span: Self) -> Self;
}

trait NativeSigned: Copy + Ord {
    type Unsigned: NativeUnsigned;

    const ZERO: Self;

    fn min_value() -> Self;
    fn max_value() -> Self;
    fn ordered(self) -> Self::Unsigned;
    fn unsigned_abs(self) -> Self::Unsigned;
    fn from_positive_magnitude(magnitude: Self::Unsigned) -> Self;
    fn from_negative_magnitude(magnitude: Self::Unsigned) -> Self;
    fn wrapping_add_rank(self, rank: Self::Unsigned) -> Self;
    fn wrapping_sub_rank(self, rank: Self::Unsigned) -> Self;
}

fn sample_unsigned_range<Capture, T>(rng: &mut CaseRng<Capture>, low: T, high: T) -> T
where
    Capture: CoverageCapture,
    T: NativeUnsigned,
{
    assert!(low <= high, "cannot sample empty range");
    let span = high.wrapping_sub(low).wrapping_add(T::ONE);
    low.wrapping_add(T::draw_rank(rng, span))
}

fn sample_signed_range<Capture, T, U>(rng: &mut CaseRng<Capture>, low: T, high: T) -> T
where
    Capture: CoverageCapture,
    T: NativeSigned<Unsigned = U>,
    U: NativeUnsigned,
{
    assert!(low <= high, "cannot sample empty range");
    let span = high
        .ordered()
        .wrapping_sub(low.ordered())
        .wrapping_add(U::ONE);
    let rank = U::draw_rank(rng, span);
    signed_value_from_rank(low, high, rank)
}

fn signed_value_from_rank<T, U>(low: T, high: T, rank: U) -> T
where
    T: NativeSigned<Unsigned = U>,
    U: NativeUnsigned,
{
    if low > T::ZERO {
        return low.wrapping_add_rank(rank);
    }
    if high < T::ZERO {
        return high.wrapping_sub_rank(rank);
    }
    if rank == U::ZERO {
        return T::ZERO;
    }

    let index = rank.wrapping_sub(U::ONE);
    let positive = high.unsigned_abs();
    let negative = low.unsigned_abs();
    let paired = positive.min(negative);
    let paired_slots = paired.saturating_mul(U::ONE.wrapping_add(U::ONE));
    if index < paired_slots {
        let magnitude = index.div2().wrapping_add(U::ONE);
        if index.is_even() {
            T::from_positive_magnitude(magnitude)
        } else {
            T::from_negative_magnitude(magnitude)
        }
    } else {
        let remaining = index.wrapping_sub(paired_slots);
        let magnitude = paired.wrapping_add(U::ONE).wrapping_add(remaining);
        if positive > negative {
            T::from_positive_magnitude(magnitude)
        } else {
            T::from_negative_magnitude(magnitude)
        }
    }
}

macro_rules! impl_unsigned_integer {
    ($($ty:ty),* $(,)?) => {
        $(
            impl NativeUnsigned for $ty {
                const ZERO: Self = 0;
                const ONE: Self = 1;

                fn to_u128(self) -> u128 {
                    self as u128
                }

                fn wrapping_add(self, rhs: Self) -> Self {
                    self.wrapping_add(rhs)
                }

                fn wrapping_sub(self, rhs: Self) -> Self {
                    self.wrapping_sub(rhs)
                }

                fn saturating_mul(self, rhs: Self) -> Self {
                    self.saturating_mul(rhs)
                }

                fn div2(self) -> Self {
                    self / 2
                }

                fn is_even(self) -> bool {
                    self.is_multiple_of(2)
                }

                fn draw_rank<Capture: CoverageCapture>(
                    rng: &mut CaseRng<Capture>,
                    span: Self,
                ) -> Self {
                    let mut bytes = [0; std::mem::size_of::<Self>()];
                    let width = if span == 0 {
                        bytes.len()
                    } else {
                        let bits = Self::BITS - span.wrapping_sub(1).leading_zeros();
                        (bits.max(1) as usize).div_ceil(8)
                    };
                    let draw = rng.fill_bytes_with_affinity(&mut bytes[..width], ByteAffinity::Zero);
                    rng.record_scalar(draw, span.to_u128());
                    let raw = Self::from_le_bytes(bytes);
                    if span == 0 { raw } else { raw % span }
                }
            }

            impl ShrinkRandom for $ty {
                fn sample<Capture: CoverageCapture>(rng: &mut CaseRng<Capture>) -> Self {
                    sample_unsigned_range(rng, 0, <$ty>::MAX)
                }
            }

            impl ShrinkRange<$ty> for Range<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    assert!(self.start < self.end, "cannot sample empty range");
                    sample_unsigned_range(rng, self.start, self.end - 1)
                }
            }

            impl ShrinkRange<$ty> for RangeInclusive<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    let (start, end) = self.into_inner();
                    sample_unsigned_range(rng, start, end)
                }
            }

            impl ShrinkRange<$ty> for RangeTo<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    assert!(self.end > 0, "cannot sample empty range");
                    sample_unsigned_range(rng, 0, self.end - 1)
                }
            }

            impl ShrinkRange<$ty> for RangeToInclusive<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    sample_unsigned_range(rng, 0, self.end)
                }
            }
        )*
    };
}

macro_rules! impl_signed_integer {
    ($($ty:ty => $unsigned:ty),* $(,)?) => {
        $(
            impl NativeSigned for $ty {
                type Unsigned = $unsigned;

                const ZERO: Self = 0;

                fn min_value() -> Self {
                    <$ty>::MIN
                }

                fn max_value() -> Self {
                    <$ty>::MAX
                }

                fn ordered(self) -> Self::Unsigned {
                    let sign_bit = 1 as $unsigned << (<$ty>::BITS - 1);
                    (self as $unsigned) ^ sign_bit
                }

                fn unsigned_abs(self) -> Self::Unsigned {
                    self.unsigned_abs()
                }

                fn from_positive_magnitude(magnitude: Self::Unsigned) -> Self {
                    magnitude as Self
                }

                fn from_negative_magnitude(magnitude: Self::Unsigned) -> Self {
                    let min_magnitude = 1 as $unsigned << (<$ty>::BITS - 1);
                    if magnitude == min_magnitude {
                        <$ty>::MIN
                    } else {
                        -(magnitude as Self)
                    }
                }

                fn wrapping_add_rank(self, rank: Self::Unsigned) -> Self {
                    self.wrapping_add(rank as Self)
                }

                fn wrapping_sub_rank(self, rank: Self::Unsigned) -> Self {
                    self.wrapping_sub(rank as Self)
                }
            }

            impl ShrinkRandom for $ty {
                fn sample<Capture: CoverageCapture>(rng: &mut CaseRng<Capture>) -> Self {
                    sample_signed_range::<Capture, $ty, $unsigned>(
                        rng,
                        <$ty as NativeSigned>::min_value(),
                        <$ty as NativeSigned>::max_value(),
                    )
                }
            }

            impl ShrinkRange<$ty> for Range<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    assert!(self.start < self.end, "cannot sample empty range");
                    sample_signed_range::<Capture, $ty, $unsigned>(rng, self.start, self.end - 1)
                }
            }

            impl ShrinkRange<$ty> for RangeInclusive<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    let (start, end) = self.into_inner();
                    sample_signed_range::<Capture, $ty, $unsigned>(rng, start, end)
                }
            }

            impl ShrinkRange<$ty> for RangeTo<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    assert!(self.end > <$ty>::MIN, "cannot sample empty range");
                    sample_signed_range::<Capture, $ty, $unsigned>(rng, <$ty>::MIN, self.end - 1)
                }
            }

            impl ShrinkRange<$ty> for RangeToInclusive<$ty> {
                #[track_caller]
                fn sample<Capture: CoverageCapture>(self, rng: &mut CaseRng<Capture>) -> $ty {
                    sample_signed_range::<Capture, $ty, $unsigned>(rng, <$ty>::MIN, self.end)
                }
            }
        )*
    };
}

impl_unsigned_integer!(u8, u16, u32, u64, u128, usize);
impl_signed_integer!(i8 => u8, i16 => u16, i32 => u32, i64 => u64, i128 => u128, isize => usize);

impl<Capture: CoverageCapture> RngCore for CaseRng<Capture> {
    fn next_u32(&mut self) -> u32 {
        self.runtime.lock().ensure_started();
        self.semantic.next_u32()
    }

    fn next_u64(&mut self) -> u64 {
        self.runtime.lock().ensure_started();
        self.semantic.next_u64()
    }

    fn fill_bytes(&mut self, dst: &mut [u8]) {
        self.runtime.lock().ensure_started();
        self.semantic.fill_bytes(dst);
    }
}

impl<Capture: CoverageCapture> CaseRuntime<Capture> {
    fn ensure_started(&mut self) {
        if self.finished || self.session.is_some() || self.start_error.is_some() {
            return;
        }
        loop {
            let session = if let Some(capture) = self.local_capture.as_mut() {
                capture.start_capture()
            } else {
                self.shared.lock().capture.start_capture()
            };
            match session {
                Ok(CaptureStart::Started(session)) => {
                    self.session = Some(session);
                    return;
                }
                Ok(CaptureStart::Busy) => {
                    std::thread::yield_now();
                }
                Err(error) => {
                    self.start_error = Some(error);
                    return;
                }
            }
        }
    }

    fn finish(
        &mut self,
        record_coverage: bool,
        case_cost: CaseCost,
    ) -> Result<CaseCoverage, String> {
        if self.finished {
            return Err("coverage already finished".to_string());
        }
        self.ensure_started();
        self.finished = true;
        let snapshot = self.trace.finish()?;
        let active = active_from_snapshot(snapshot, self.origin.clone());

        let session = self.session.take();
        if let Some(mut capture) = self.local_capture.take() {
            let outcome = finish_capture(
                &mut capture,
                session,
                self.start_error.take(),
                record_coverage,
            );
            match outcome {
                Ok(outcome) => {
                    let mut state = self.shared.lock();
                    merge_finished_execution(&mut state.core, active, outcome, case_cost)
                }
                Err(error) => {
                    let mut state = self.shared.lock();
                    state.stats.executed += 1;
                    state.active_cases = state.active_cases.saturating_sub(1);
                    Err(error)
                }
            }
        } else {
            let mut state = self.shared.lock();
            let outcome = finish_capture(
                &mut state.capture,
                session,
                self.start_error.take(),
                record_coverage,
            );
            match outcome {
                Ok(outcome) => {
                    merge_finished_execution(&mut state.core, active, outcome, case_cost)
                }
                Err(error) => {
                    state.stats.executed += 1;
                    state.active_cases = state.active_cases.saturating_sub(1);
                    Err(error)
                }
            }
        }
    }
}

impl<Capture> Drop for CaseRuntime<Capture>
where
    Capture: CoverageCapture,
{
    fn drop(&mut self) {
        if !self.finished {
            let _ = self.finish(true, CaseCost::zero());
        }
    }
}

fn active_from_snapshot(snapshot: TraceSnapshot, origin: CandidateOrigin) -> Active {
    Active {
        seed: snapshot.seed,
        case: snapshot.trace,
        trace: snapshot.prefix,
        draws: clip_draws(snapshot.draws),
        scalars: clip_scalars(snapshot.scalars),
        sequences: snapshot.sequences,
        bytes_consumed: snapshot.bytes_consumed,
        origin,
    }
}

fn clip_draws(draws: Vec<DrawSpan>) -> Vec<DrawSpan> {
    draws
        .into_iter()
        .filter_map(|draw| {
            if draw.is_empty() || draw.start >= MAX_PREFIX_LEN {
                return None;
            }
            Some(DrawSpan {
                start: draw.start,
                end: draw.end.min(MAX_PREFIX_LEN),
                affinity: draw.affinity,
            })
        })
        .collect()
}

fn clip_scalars(scalars: Vec<ScalarSpan>) -> Vec<ScalarSpan> {
    scalars
        .into_iter()
        .filter(|scalar| !scalar.is_empty() && scalar.end <= MAX_PREFIX_LEN)
        .collect()
}

struct FinishedCapture {
    feedback: Option<ExecutionFeedback>,
}

fn finish_capture<Capture>(
    capture: &mut Capture,
    session: Option<Capture::Session>,
    start_error: Option<String>,
    record_coverage: bool,
) -> Result<FinishedCapture, String>
where
    Capture: CoverageCapture,
{
    if !record_coverage {
        if let Some(session) = session {
            capture.discard_capture(session)?;
        }
        return Ok(FinishedCapture { feedback: None });
    }

    if let Some(error) = start_error {
        return Err(error);
    }
    let session = session.ok_or_else(|| "coverage capture never started".to_string())?;
    Ok(FinishedCapture {
        feedback: Some(capture.finish_capture(session)?),
    })
}

fn merge_finished_execution(
    state: &mut StateCore,
    active: Active,
    finished: FinishedCapture,
    case_cost: CaseCost,
) -> Result<CaseCoverage, String> {
    state.stats.executed += 1;
    state.active_cases = state.active_cases.saturating_sub(1);
    let mutation_ids = active.origin.mutation_ids().to_vec();

    let Some(feedback) = finished.feedback else {
        record_discarded_goal_execution(state, &active.origin, &mutation_ids);
        return Ok(CaseCoverage::with_cost(
            CaseCost::zero(),
            0,
            0,
            active.bytes_consumed,
        ));
    };
    merge_dictionary_values(state, feedback.dictionary);

    let coverage = feedback.features;
    let run_coverage = CaseCoverage::with_cost(
        case_cost,
        coverage.len(),
        feedback.hit_count_weight,
        active.bytes_consumed,
    );
    record_finished_goal_execution(state, active, run_coverage, coverage);

    Ok(run_coverage)
}
